# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  # will start web server that's accessible from localhost:8000 on host
  # tested with http://dl.dropbox.com/u/1537815/precise64.box
  config.vm.forward_port 80, 8000

  # chef solo provisioning
  config.vm.provision :chef_solo do |chef|
    # set this to the relative or absolute path to the
    # cookbooks and site-cookbooks dirs
    chef.cookbooks_path = ["../../cookbooks","../../site-cookbooks"]
    # set this to the relative or absolute path to the
    # mytardis-chef roles directory (or your own)    
    chef.roles_path = "../../roles"
    chef.add_recipe "mytardis"
    chef.log_level = :debug
    chef.json = {"chef_environment"=>"_default",
                   "run_list"=>["role[mytardis]"],
                    "postgresql"=>
                    {
                      "password"=>{
                        "postgres"=>"md58c34d6a23b00817aa5ef7c620638f491"}
                    },
                    "name"=>"mytardis-chefsolo"
                }
  end 
end
