# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  # will start web server that's accessible from localhost:8000 on host
  # tested with http://files.vagrantup.com/lucid32.box
  config.vm.forward_port 80, 8000

  # chef solo provisioning
  config.vm.provision :chef_solo do |chef|
    # set this to the relative or absolute path to the
    # cookbooks and site-cookbooks dirs
    chef.cookbooks_path = ["../../cookbooks","../../site-cookbooks"]
    # set this to the relative or absolute path to the
    # mytardis-chef roles directory (or your own)    
    chef.roles_path = "../../roles"
    chef.add_recipe "mytardis"
    chef.log_level = :debug
    chef.json = {"chef_environment"=>"_default",
                   "run_list"=>["role[mytardis]"],
                    "normal"=>
                    {"postgresql"=>
                      {
                        "dir"=>"/var/lib/pgsql/data",
                        "password"=>{
                        "postgres"=>"insertpasswordhere"}},
                        "tags"=>[]},
                    "name"=>"mytardis-chefsolo"
                }  
  end 
end
